/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ANTHROPIC_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ANTHROPIC_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ANTHROPIC_MODEL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FileOrganizerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_REDIRECT_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LLM_ADAPTER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_MODEL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TelegramBot": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}